[colors.bright]
black = "0x737d87"
blue = "0x59c2ff"
cyan = "0x5ccfe6"
green = "0xc2d94c"
magenta = "0xb77ee0"
red = "0xff3333"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x73d0ff"
cyan = "0x83CEC6"
green = "0xbae67e"
magenta = "0xd4bfff"
red = "0xf34a4a"
white = "0xf2f2f2"
yellow = "0xffee99"

[colors.primary]
background = "0x0D1017"
foreground = "0xe6e1cf"

[font]
size = 9
# family = "NotoMono Nerd Font"

# [font.bold]
# family = "NotoMono Nerd Font"
# style = "Bold"
#
# [font.italic]
# family = "NotoMono Nerd Font"
# style = "Italic"

[font.normal]
family = "NotoMono Nerd Font"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

# [url]
# launcher = "xdg-open"
# modifiers = "Control"

[window]
dynamic_title = true
opacity = 0.98
